name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Runs tests only on the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # Install dependencies if requirements.txt exists
          pip install pytest  # Ensure pytest is installed

      - name: Run Pytest
        run: pytest --maxfail=5 --disable-warnings
